name: 'Android Environment multi-command runner'
description: 'A docker image that sets up a basic environment for building and running an android project.'
inputs:
    command1:
        description: 'The first command to run.'
        required: true
        default: ''
    command2:
        description: 'The second command to run.'
        required: false
        default: ''
    command3:
        description: 'The third command to run.'
        required: false
        default: ''
    command4:
        description: 'The fourth command to run.'
        required: false
        default: ''
    command5:
        description: 'The fifth command to run.'
        required: false
        default: ''
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command1 }}
    - ${{ inputs.command2 }}
    - ${{ inputs.command3 }}
    - ${{ inputs.command4 }}
    - ${{ inputs.command5 }}