# name: 'Android Environment multi-command runner'
# description: 'A docker image that sets up a basic environment for building and running an android project.'
# inputs:
#     command1:
#         description: 'The first command to run.'
#         required: true
#         default: ''
#     command2:
#         description: 'The second command to run.'
#         required: false
#         default: ''
#     command3:
#         description: 'The third command to run.'
#         required: false
#         default: ''
#     command4:
#         description: 'The fourth command to run.'
#         required: false
#         default: ''
#     command5:
#         description: 'The fifth command to run.'
#         required: false
#         default: ''
  
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.command1 }}
#     - ${{ inputs.command2 }}
#     - ${{ inputs.command3 }}
#     - ${{ inputs.command4 }}
#     - ${{ inputs.command5 }}
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}