name: CI

on: [push]

jobs:
  testing_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v2 
      - name: "Multi-command runner"
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
