name: CI

on: [push]

jobs:
  testing_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v2 
      - name: "Multi-command runner"
        uses: ./
        with:
          working-dir: 'sample-project'
          command1: 'echo "...Starting..."'
          command2: './gradlew app:assembleDebug'
          command3: './gradlew lint'
          command4: './gradlew test'
          command5: 'echo "...Finished..."'