name: CI

on: [push]

jobs:
  testing_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v2 
      - name: "Multi-command runner"
        uses: ./
        with:
          working-dir: '.'
          command1: 'echo "Starting runner.."'
          command2: 'app:assembleDebug'
          command3: 'lint'
          command4: 'test'
          command4: 'echo "Finished"'
