name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out 
        uses: actions/checkout@v2
      - name: "Multi-command runner"
        uses: ./
        id: Runner
        with: 
          command1: 'Giorgos'
          command2: 'Neokleous' 
